package PRP;


import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno1
 */
public class SN_add extends javax.swing.JFrame {
    
    public crud_db OP = new crud_db();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pagina_Principal.class.getName());

    
    
    /**
     * Creates new form Pagina_Principal
     */
    
    crud_db crud = new crud_db();
    
    public SN_add() {
        initComponents();
       // if(crud.conectar);
// Redimensiona para 20x20 pixels
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Principal = new javax.swing.JPanel();
        online = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtunidade = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        Enviar = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        LB_nome = new javax.swing.JLabel();
        LB_nome1 = new javax.swing.JLabel();
        LB_nome2 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        Barra_Menu = new javax.swing.JMenuBar();
        menu_principal = new javax.swing.JMenu();
        menu_gestao = new javax.swing.JMenu();
        Gestao_Novo_Cliente = new javax.swing.JMenuItem();
        Gestao_Listar_Cliente = new javax.swing.JMenuItem();
        Gestao_Editar_Cliente = new javax.swing.JMenuItem();
        Gestao_Separador = new javax.swing.JPopupMenu.Separator();
        Gestao_Novo_Produto = new javax.swing.JMenuItem();
        Gestao_Listar_Produto = new javax.swing.JMenuItem();
        menu_sensor = new javax.swing.JMenu();
        NovoSensor = new javax.swing.JMenuItem();
        ListarSensor = new javax.swing.JMenuItem();
        EditarSensor = new javax.swing.JMenuItem();
        menu_sobre = new javax.swing.JMenu();
        menu_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(512, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Painel_Principal.setBackground(new java.awt.Color(0, 51, 102));
        Painel_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        online.setText("Online");
        Painel_Principal.add(online, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        footer.setBackground(new java.awt.Color(0, 153, 153));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setText("Sair");
        exit.addActionListener(this::exitActionPerformed);
        footer.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        Painel_Principal.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 480, 40));

        header.setBackground(new java.awt.Color(0, 153, 153));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Title.setText("Adcionar Sensor");
        header.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 140, 40));

        Painel_Principal.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 40));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtunidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 132, 170, 30));
        jPanel1.add(txttipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 82, 170, 30));

        Enviar.setText("Enviar");
        Enviar.addActionListener(this::EnviarActionPerformed);
        jPanel1.add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));
        jPanel1.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 42, 170, 30));

        LB_nome.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        LB_nome.setText("Nome:");
        jPanel1.add(LB_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 60, 30));

        LB_nome1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        LB_nome1.setText("Unidade:");
        jPanel1.add(LB_nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 30));

        LB_nome2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        LB_nome2.setText("Tipo:");
        jPanel1.add(LB_nome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 60, 30));

        Voltar.setText("Voltar");
        Voltar.addActionListener(this::VoltarActionPerformed);
        jPanel1.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        Painel_Principal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 460, 380));

        getContentPane().add(Painel_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        menu_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/home.png"))); // NOI18N
        menu_principal.setMnemonic('P');
        menu_principal.setText("Principal");
        menu_principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_principalMouseClicked(evt);
            }
        });
        Barra_Menu.add(menu_principal);

        menu_gestao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/gestao.png"))); // NOI18N
        menu_gestao.setMnemonic('G');
        menu_gestao.setText("Gestão");

        Gestao_Novo_Cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Gestao_Novo_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/NC.png"))); // NOI18N
        Gestao_Novo_Cliente.setMnemonic('C');
        Gestao_Novo_Cliente.setText("Novo Cliente");
        Gestao_Novo_Cliente.addActionListener(this::Gestao_Novo_ClienteActionPerformed);
        menu_gestao.add(Gestao_Novo_Cliente);

        Gestao_Listar_Cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Gestao_Listar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/LC.png"))); // NOI18N
        Gestao_Listar_Cliente.setMnemonic('L');
        Gestao_Listar_Cliente.setText("Listar Cliente");
        Gestao_Listar_Cliente.addActionListener(this::Gestao_Listar_ClienteActionPerformed);
        menu_gestao.add(Gestao_Listar_Cliente);

        Gestao_Editar_Cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Gestao_Editar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/CLEDI.png"))); // NOI18N
        Gestao_Editar_Cliente.setText("Editar Cliente");
        Gestao_Editar_Cliente.addActionListener(this::Gestao_Editar_ClienteActionPerformed);
        menu_gestao.add(Gestao_Editar_Cliente);
        menu_gestao.add(Gestao_Separador);

        Gestao_Novo_Produto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Gestao_Novo_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/NP.png"))); // NOI18N
        Gestao_Novo_Produto.setMnemonic('N');
        Gestao_Novo_Produto.setText("Novo Produto");
        menu_gestao.add(Gestao_Novo_Produto);

        Gestao_Listar_Produto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Gestao_Listar_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/LP.png"))); // NOI18N
        Gestao_Listar_Produto.setMnemonic('R');
        Gestao_Listar_Produto.setText("Listar Produto");
        menu_gestao.add(Gestao_Listar_Produto);

        Barra_Menu.add(menu_gestao);

        menu_sensor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Sensor.png"))); // NOI18N
        menu_sensor.setMnemonic('S');
        menu_sensor.setText("Sensor");

        NovoSensor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        NovoSensor.setText("Novo Sensor");
        NovoSensor.addActionListener(this::NovoSensorActionPerformed);
        menu_sensor.add(NovoSensor);

        ListarSensor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ListarSensor.setText("Listar Sensor");
        ListarSensor.addActionListener(this::ListarSensorActionPerformed);
        menu_sensor.add(ListarSensor);

        EditarSensor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        EditarSensor.setText("Editar Sensor");
        EditarSensor.addActionListener(this::EditarSensorActionPerformed);
        menu_sensor.add(EditarSensor);

        Barra_Menu.add(menu_sensor);

        menu_sobre.setIcon(new javax.swing.ImageIcon("C:\\Users\\betue\\Downloads\\round.png")); // NOI18N
        menu_sobre.setMnemonic('O');
        menu_sobre.setText("Sobre");
        Barra_Menu.add(menu_sobre);

        menu_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sair.png"))); // NOI18N
        menu_sair.setMnemonic('A');
        menu_sair.setText("Sair");
        menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sairMouseClicked(evt);
            }
        });
        Barra_Menu.add(menu_sair);

        setJMenuBar(Barra_Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
    OP.insertSensor(txtnome.getText(), txttipo.getText(), Integer.parseInt(txtunidade.getText()));
    }//GEN-LAST:event_EnviarActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
        new Pagina_Principal().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void Gestao_Novo_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestao_Novo_ClienteActionPerformed
        dispose();
        new CL_add().setVisible(true);
    }//GEN-LAST:event_Gestao_Novo_ClienteActionPerformed

    private void Gestao_Listar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestao_Listar_ClienteActionPerformed
        dispose();
        new CL_listar().setVisible(true);
    }//GEN-LAST:event_Gestao_Listar_ClienteActionPerformed

    private void Gestao_Editar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestao_Editar_ClienteActionPerformed
        dispose();
        new CL_updt().setVisible(true);
    }//GEN-LAST:event_Gestao_Editar_ClienteActionPerformed

    private void NovoSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoSensorActionPerformed
        dispose();
        new SN_add().setVisible(true);
    }//GEN-LAST:event_NovoSensorActionPerformed

    private void ListarSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarSensorActionPerformed

    }//GEN-LAST:event_ListarSensorActionPerformed

    private void EditarSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarSensorActionPerformed
        dispose();
        new SN_updt().setVisible(true);
    }//GEN-LAST:event_EditarSensorActionPerformed

    private void menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menu_sairMouseClicked

    private void menu_principalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_principalMouseClicked
        dispose();
        new Pagina_Principal().setVisible(true);
    }//GEN-LAST:event_menu_principalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pagina_Principal().setVisible(true));
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barra_Menu;
    private javax.swing.JMenuItem EditarSensor;
    private javax.swing.JButton Enviar;
    private javax.swing.JMenuItem Gestao_Editar_Cliente;
    private javax.swing.JMenuItem Gestao_Listar_Cliente;
    private javax.swing.JMenuItem Gestao_Listar_Produto;
    private javax.swing.JMenuItem Gestao_Novo_Cliente;
    private javax.swing.JMenuItem Gestao_Novo_Produto;
    private javax.swing.JPopupMenu.Separator Gestao_Separador;
    private javax.swing.JLabel LB_nome;
    private javax.swing.JLabel LB_nome1;
    private javax.swing.JLabel LB_nome2;
    private javax.swing.JMenuItem ListarSensor;
    private javax.swing.JMenuItem NovoSensor;
    private javax.swing.JPanel Painel_Principal;
    private javax.swing.JLabel Title;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton exit;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menu_gestao;
    private javax.swing.JMenu menu_principal;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JMenu menu_sensor;
    private javax.swing.JMenu menu_sobre;
    private javax.swing.JLabel online;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txttipo;
    private javax.swing.JTextField txtunidade;
    // End of variables declaration//GEN-END:variables
}
