/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno1
 */
public class CL_add extends javax.swing.JFrame {
    public crud_db OP = new crud_db();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pagina_Principal.class.getName());

    /**
     * Creates new form CL_add
     */
    public CL_add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Principal = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        formPanel = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        lblDataNasc = new javax.swing.JLabel();
        lblNif = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        txtNif = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblcartaoId = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtCartaoId = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        lblRedesSociais = new javax.swing.JLabel();
        txtRedesSociais = new javax.swing.JTextField();
        lblMorada = new javax.swing.JLabel();
        txtMorada = new javax.swing.JTextField();
        lblZonaPostal = new javax.swing.JLabel();
        lblCodigoPostal = new javax.swing.JLabel();
        txtZonaPostal = new javax.swing.JTextField();
        txtCodigoPostal = new javax.swing.JTextField();
        lblNacionalidade = new javax.swing.JLabel();
        lblDataRegisto = new javax.swing.JLabel();
        lblimagem = new javax.swing.JLabel();
        lblObs = new javax.swing.JLabel();
        txtNacionalidade = new javax.swing.JTextField();
        txtDataRegisto = new javax.swing.JTextField();
        txtimagem = new javax.swing.JTextField();
        txtObs = new javax.swing.JTextField();
        Voltar = new javax.swing.JButton();
        Enviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 700));
        setMinimumSize(new java.awt.Dimension(650, 700));
        setPreferredSize(new java.awt.Dimension(650, 700));

        Painel_Principal.setBackground(new java.awt.Color(0, 51, 102));
        Painel_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 153, 153));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Title.setText("Adicionar Cliente");
        header.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 180, 40));

        Painel_Principal.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 40));

        footer.setBackground(new java.awt.Color(0, 153, 153));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setText("Sair");
        exit.addActionListener(this::exitActionPerformed);
        footer.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        Painel_Principal.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 620, 40));

        formPanel.setBackground(new java.awt.Color(0, 153, 153));
        formPanel.setMaximumSize(new java.awt.Dimension(600, 850));
        formPanel.setMinimumSize(new java.awt.Dimension(600, 850));
        formPanel.setPreferredSize(new java.awt.Dimension(600, 850));
        formPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblNome.setText("Nome");
        formPanel.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 25));
        formPanel.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 350, 25));

        lblCategoria.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblCategoria.setText("Categoria");
        formPanel.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 25));
        formPanel.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 350, 25));

        lblDataNasc.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDataNasc.setText("Data de Nascimento");
        formPanel.add(lblDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, 25));

        lblNif.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblNif.setText("NIF");
        formPanel.add(lblNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 25));
        formPanel.add(txtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 350, 25));
        formPanel.add(txtNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 350, 25));

        lblEmail.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblEmail.setText("Email");
        formPanel.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 180, 25));

        lblGenero.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblGenero.setText("Gênero");
        formPanel.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 25));

        lblcartaoId.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblcartaoId.setText("CartãoId");
        formPanel.add(lblcartaoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, 25));

        lblTelefone.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblTelefone.setText("Telefone");
        formPanel.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, 25));
        formPanel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 350, 25));
        formPanel.add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 350, 25));
        formPanel.add(txtCartaoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 350, 25));
        formPanel.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 350, 25));

        lblRedesSociais.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblRedesSociais.setText("Redes Sociais");
        formPanel.add(lblRedesSociais, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 180, 25));
        formPanel.add(txtRedesSociais, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 350, 25));

        lblMorada.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblMorada.setText("Morada");
        formPanel.add(lblMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 180, 25));
        formPanel.add(txtMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 350, 25));

        lblZonaPostal.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblZonaPostal.setText("Zona Postal");
        formPanel.add(lblZonaPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 180, 25));

        lblCodigoPostal.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblCodigoPostal.setText("Código Postal");
        formPanel.add(lblCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 180, 25));
        formPanel.add(txtZonaPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 350, 25));
        formPanel.add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 350, 25));

        lblNacionalidade.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblNacionalidade.setText("Nacionalidade");
        formPanel.add(lblNacionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 180, 25));

        lblDataRegisto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDataRegisto.setText("Data de Registo");
        formPanel.add(lblDataRegisto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 180, 25));

        lblimagem.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblimagem.setText("Imagem");
        formPanel.add(lblimagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 180, 25));

        lblObs.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblObs.setText("OBS");
        formPanel.add(lblObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 180, 25));
        formPanel.add(txtNacionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 350, 25));
        formPanel.add(txtDataRegisto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 350, 25));
        formPanel.add(txtimagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, 350, 25));
        formPanel.add(txtObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, 350, 25));

        Voltar.setText("Voltar");
        Voltar.addActionListener(this::VoltarActionPerformed);
        formPanel.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 710, -1, -1));

        Enviar.setText("Enviar");
        Enviar.addActionListener(this::EnviarActionPerformed);
        formPanel.add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 710, -1, -1));

        scrollPane.setViewportView(formPanel);

        Painel_Principal.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 600, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
        new Pagina_Principal().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        OP.insertCliente(nome_cliente, categoria_cliente, data_nasc, WIDTH, email, genero, PROPERTIES, HIDE_ON_CLOSE, redes_sociais, morada, NORMAL, NORMAL, nacionalidade, pais, data_registo, imagem, OBS);
    }//GEN-LAST:event_EnviarActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CL_add().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JPanel Painel_Principal;
    private javax.swing.JLabel Title;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton exit;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodigoPostal;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblDataRegisto;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblMorada;
    private javax.swing.JLabel lblNacionalidade;
    private javax.swing.JLabel lblNif;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblRedesSociais;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblZonaPostal;
    private javax.swing.JLabel lblcartaoId;
    private javax.swing.JLabel lblimagem;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField txtCartaoId;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtDataRegisto;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtMorada;
    private javax.swing.JTextField txtNacionalidade;
    private javax.swing.JTextField txtNif;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtObs;
    private javax.swing.JTextField txtRedesSociais;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtZonaPostal;
    private javax.swing.JTextField txtimagem;
    // End of variables declaration//GEN-END:variables
}
