
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno1
 */
public class CL_listar extends javax.swing.JFrame {
    public crud_db OP = new crud_db();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pagina_Principal.class.getName());

    /**
     * Creates new form
     */
    public CL_listar() {
        initComponents();
        CarregarDados();
        loadTable_Clientes();
    }
    private void CarregarDados(){
    if(OP.TestarLigacao()){
        online.setForeground(Color.green);
        online.setText("Ligação DB: Ativa");
    }else{
    online.setForeground(Color.red);
    online.setText("Ligação DB: Desativa");
    }
    }
    public void loadTable_Clientes(){
        DefaultTableModel model_tab_cliente = (DefaultTableModel) tblCL.getModel();
        model_tab_cliente.setNumRows(0);
        try {
            for(Object[] line: OP.getAllCliente()){
                model_tab_cliente.addRow(line);
            }
        } catch (SQLException ex) {
            System.getLogger(CL_listar.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Principal = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        formPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCL = new javax.swing.JTable();
        online = new javax.swing.JLabel();
        Barra_Menu = new javax.swing.JMenuBar();
        menu_principal = new javax.swing.JMenu();
        menu_gestao = new javax.swing.JMenu();
        Gestao_Novo_Cliente = new javax.swing.JMenuItem();
        Gestao_Listar_Cliente = new javax.swing.JMenuItem();
        Gestao_Editar_Cliente = new javax.swing.JMenuItem();
        Gestao_Separador = new javax.swing.JPopupMenu.Separator();
        Gestao_Novo_Produto = new javax.swing.JMenuItem();
        Gestao_Listar_Produto = new javax.swing.JMenuItem();
        menu_sensor = new javax.swing.JMenu();
        NovoSensor = new javax.swing.JMenuItem();
        ListarSensor = new javax.swing.JMenuItem();
        EditarSensor = new javax.swing.JMenuItem();
        menu_sobre = new javax.swing.JMenu();
        menu_sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 700));

        Painel_Principal.setBackground(new java.awt.Color(0, 51, 102));
        Painel_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 153, 153));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Title.setText("Listar Clientes");
        header.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 180, 40));

        Painel_Principal.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 40));

        footer.setBackground(new java.awt.Color(0, 153, 153));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setText("Sair");
        exit.addActionListener(this::exitActionPerformed);
        footer.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        Painel_Principal.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 620, 40));

        formPanel.setBackground(new java.awt.Color(0, 153, 153));
        formPanel.setMaximumSize(new java.awt.Dimension(1500, 850));
        formPanel.setMinimumSize(new java.awt.Dimension(1500, 850));
        formPanel.setPreferredSize(new java.awt.Dimension(1500, 850));
        formPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Categoria", "Nascimento", "NIF", "Email", "Genero", "CC", "Telefone", "Redes Sociais", "Morada", "Zona Postal", "Código Postal", "Nacionalidade", "Pais", "Data Registo", "Imagem", "Observações"
            }
        ));
        jScrollPane1.setViewportView(tblCL);

        formPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, 1480, 410));

        online.setText("Online");
        formPanel.add(online, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, -1));

        scrollPane.setViewportView(formPanel);

        Painel_Principal.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 600, 540));

        menu_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/home.png"))); // NOI18N
        menu_principal.setMnemonic('P');
        menu_principal.setText("Principal");
        menu_principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_principalMouseClicked(evt);
            }
        });
        Barra_Menu.add(menu_principal);

        menu_gestao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/gestao.png"))); // NOI18N
        menu_gestao.setMnemonic('G');
        menu_gestao.setText("Gestão");

        Gestao_Novo_Cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Gestao_Novo_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/NC.png"))); // NOI18N
        Gestao_Novo_Cliente.setMnemonic('C');
        Gestao_Novo_Cliente.setText("Novo Cliente");
        Gestao_Novo_Cliente.addActionListener(this::Gestao_Novo_ClienteActionPerformed);
        menu_gestao.add(Gestao_Novo_Cliente);

        Gestao_Listar_Cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Gestao_Listar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/LC.png"))); // NOI18N
        Gestao_Listar_Cliente.setMnemonic('L');
        Gestao_Listar_Cliente.setText("Listar Cliente");
        Gestao_Listar_Cliente.addActionListener(this::Gestao_Listar_ClienteActionPerformed);
        menu_gestao.add(Gestao_Listar_Cliente);

        Gestao_Editar_Cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Gestao_Editar_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/CLEDI.png"))); // NOI18N
        Gestao_Editar_Cliente.setText("Editar Cliente");
        Gestao_Editar_Cliente.addActionListener(this::Gestao_Editar_ClienteActionPerformed);
        menu_gestao.add(Gestao_Editar_Cliente);
        menu_gestao.add(Gestao_Separador);

        Gestao_Novo_Produto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Gestao_Novo_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/NP.png"))); // NOI18N
        Gestao_Novo_Produto.setMnemonic('N');
        Gestao_Novo_Produto.setText("Novo Produto");
        menu_gestao.add(Gestao_Novo_Produto);

        Gestao_Listar_Produto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Gestao_Listar_Produto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/LP.png"))); // NOI18N
        Gestao_Listar_Produto.setMnemonic('R');
        Gestao_Listar_Produto.setText("Listar Produto");
        menu_gestao.add(Gestao_Listar_Produto);

        Barra_Menu.add(menu_gestao);

        menu_sensor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Sensor.png"))); // NOI18N
        menu_sensor.setMnemonic('S');
        menu_sensor.setText("Sensor");

        NovoSensor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        NovoSensor.setText("Novo Sensor");
        NovoSensor.addActionListener(this::NovoSensorActionPerformed);
        menu_sensor.add(NovoSensor);

        ListarSensor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ListarSensor.setText("Listar Sensor");
        ListarSensor.addActionListener(this::ListarSensorActionPerformed);
        menu_sensor.add(ListarSensor);

        EditarSensor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        EditarSensor.setText("Editar Sensor");
        EditarSensor.addActionListener(this::EditarSensorActionPerformed);
        menu_sensor.add(EditarSensor);

        Barra_Menu.add(menu_sensor);

        menu_sobre.setIcon(new javax.swing.ImageIcon("C:\\Users\\betue\\Downloads\\round.png")); // NOI18N
        menu_sobre.setMnemonic('O');
        menu_sobre.setText("Sobre");
        Barra_Menu.add(menu_sobre);

        menu_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/sair.png"))); // NOI18N
        menu_sair.setMnemonic('A');
        menu_sair.setText("Sair");
        menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sairMouseClicked(evt);
            }
        });
        Barra_Menu.add(menu_sair);

        setJMenuBar(Barra_Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void menu_principalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_principalMouseClicked
        dispose();
        new Pagina_Principal().setVisible(true);
    }//GEN-LAST:event_menu_principalMouseClicked

    private void Gestao_Novo_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestao_Novo_ClienteActionPerformed
        dispose();
        new CL_add().setVisible(true);
    }//GEN-LAST:event_Gestao_Novo_ClienteActionPerformed

    private void Gestao_Listar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestao_Listar_ClienteActionPerformed
        dispose();
        new CL_listar().setVisible(true);
    }//GEN-LAST:event_Gestao_Listar_ClienteActionPerformed

    private void Gestao_Editar_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gestao_Editar_ClienteActionPerformed
        dispose();
        new CL_updt().setVisible(true);
    }//GEN-LAST:event_Gestao_Editar_ClienteActionPerformed

    private void NovoSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoSensorActionPerformed
        dispose();
        new SN_add().setVisible(true);
    }//GEN-LAST:event_NovoSensorActionPerformed

    private void ListarSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarSensorActionPerformed

    }//GEN-LAST:event_ListarSensorActionPerformed

    private void EditarSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarSensorActionPerformed
        dispose();
        new SN_updt().setVisible(true);
    }//GEN-LAST:event_EditarSensorActionPerformed

    private void menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_menu_sairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CL_listar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barra_Menu;
    private javax.swing.JMenuItem EditarSensor;
    private javax.swing.JMenuItem Gestao_Editar_Cliente;
    private javax.swing.JMenuItem Gestao_Listar_Cliente;
    private javax.swing.JMenuItem Gestao_Listar_Produto;
    private javax.swing.JMenuItem Gestao_Novo_Cliente;
    private javax.swing.JMenuItem Gestao_Novo_Produto;
    private javax.swing.JPopupMenu.Separator Gestao_Separador;
    private javax.swing.JMenuItem ListarSensor;
    private javax.swing.JMenuItem NovoSensor;
    private javax.swing.JPanel Painel_Principal;
    private javax.swing.JLabel Title;
    private javax.swing.JButton exit;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu_gestao;
    private javax.swing.JMenu menu_principal;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JMenu menu_sensor;
    private javax.swing.JMenu menu_sobre;
    private javax.swing.JLabel online;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblCL;
    // End of variables declaration//GEN-END:variables
}
