
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno1
 */
public class CL_listar extends javax.swing.JFrame {
    public crud_db OP = new crud_db();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pagina_Principal.class.getName());

    /**
     * Creates new form
     */
    public CL_listar() {
        initComponents();
        CarregarDados();
        loadTable_Clientes();
    }
    private void CarregarDados(){
    if(OP.TestarLigacao()){
        online.setForeground(Color.green);
        online.setText("Ligação DB: Ativa");
    }else{
    online.setForeground(Color.red);
    online.setText("Ligação DB: Desativa");
    }
    }
    public void loadTable_Clientes(){
        DefaultTableModel model_tab_cliente = (DefaultTableModel) tblCL.getModel();
        model_tab_cliente.setNumRows(0);
        try {
            for(Object[] line: OP.getAllCliente()){
                model_tab_cliente.addRow(line);
            }
        } catch (SQLException ex) {
            System.getLogger(CL_listar.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Principal = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        formPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCL = new javax.swing.JTable();
        online = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 700));

        Painel_Principal.setBackground(new java.awt.Color(0, 51, 102));
        Painel_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 153, 153));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Title.setText("Listar Clientes");
        header.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 180, 40));

        Painel_Principal.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 40));

        footer.setBackground(new java.awt.Color(0, 153, 153));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setText("Sair");
        exit.addActionListener(this::exitActionPerformed);
        footer.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        Painel_Principal.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 620, 40));

        formPanel.setBackground(new java.awt.Color(0, 153, 153));
        formPanel.setMaximumSize(new java.awt.Dimension(1500, 850));
        formPanel.setMinimumSize(new java.awt.Dimension(1500, 850));
        formPanel.setPreferredSize(new java.awt.Dimension(1500, 850));
        formPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Categoria", "Nascimento", "NIF", "Email", "Genero", "CC", "Telefone", "Redes Sociais", "Morada", "Zona Postal", "Código Postal", "Nacionalidade", "Pais", "Data Registo", "Imagem", "Observações"
            }
        ));
        jScrollPane1.setViewportView(tblCL);

        formPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, 1480, 410));

        online.setText("Online");
        formPanel.add(online, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, -1));

        scrollPane.setViewportView(formPanel);

        Painel_Principal.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 600, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CL_listar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_Principal;
    private javax.swing.JLabel Title;
    private javax.swing.JButton exit;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel online;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblCL;
    // End of variables declaration//GEN-END:variables
}
