/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JOptionPane;
import java.util.Map;
/**
 *
 * @author Aluno1
 */
public class CL_updt extends javax.swing.JFrame {
    public crud_db OP = new crud_db();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pagina_Principal.class.getName());

    /**
     * Creates new form CL_add
     */
    public CL_updt() {
        initComponents();
    }
    
    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {
    String codigoStr = txtCodId.getText().trim();
    if (codigoStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Digite um código de cliente para buscar.");
        return;
    }
    int codigo;
    try {
        codigo = Integer.parseInt(codigoStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Código inválido.");
        return;
    }

    Map<String, Object> dados = OP.buscarClientePorCodigo(codigo);
    if (dados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Cliente não encontrado.");
        return;
    }

    // Preencher os campos com os dados atuais
    txtNome.setText((String) dados.get("nome_cliente"));
    txtCategoria.setText((String) dados.get("categoria_cliente"));
    
    java.sql.Date dataNasc = (java.sql.Date) dados.get("data_nasc");
    if (dataNasc != null) txtDataNasc.setText(dataNasc.toString());
    else txtDataNasc.setText("");
    
    txtNif.setText(String.valueOf(dados.get("nif")));
    txtEmail.setText((String) dados.get("email"));
    txtGenero.setText((String) dados.get("genero"));
    txtCartaoId.setText(String.valueOf(dados.get("cartao_identificacao")));
    txtTelefone.setText(String.valueOf(dados.get("numero_telefone")));
    txtRedesSociais.setText((String) dados.get("redes_sociais"));
    txtMorada.setText((String) dados.get("morada"));
    txtZonaPostal.setText(String.valueOf(dados.get("zona_postal")));
    txtCodigoPostal.setText(String.valueOf(dados.get("cod_postal")));
    txtNacionalidade.setText((String) dados.get("nacionalidade"));
    txtPais.setText((String) dados.get("pais"));
    
    java.sql.Date dataRegisto = (java.sql.Date) dados.get("data_registo");
    if (dataRegisto != null) txtDataRegisto.setText(dataRegisto.toString());
    else txtDataRegisto.setText("");
    
    txtimagem.setText((String) dados.get("imagem"));
    txtObs.setText((String) dados.get("OBS"));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Principal = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        formPanel = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        lblDataNasc = new javax.swing.JLabel();
        lblNif = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JTextField();
        txtNif = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblcartaoId = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtCartaoId = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        lblRedesSociais = new javax.swing.JLabel();
        txtRedesSociais = new javax.swing.JTextField();
        lblMorada = new javax.swing.JLabel();
        txtMorada = new javax.swing.JTextField();
        lblZonaPostal = new javax.swing.JLabel();
        lblCodigoPostal = new javax.swing.JLabel();
        txtZonaPostal = new javax.swing.JTextField();
        txtCodigoPostal = new javax.swing.JTextField();
        lblNacionalidade = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        lblimagem = new javax.swing.JLabel();
        lblObs = new javax.swing.JLabel();
        txtNacionalidade = new javax.swing.JTextField();
        txtPais = new javax.swing.JTextField();
        txtimagem = new javax.swing.JTextField();
        txtObs = new javax.swing.JTextField();
        Voltar = new javax.swing.JButton();
        Enviar = new javax.swing.JButton();
        lblDataRegisto = new javax.swing.JLabel();
        txtDataRegisto = new javax.swing.JTextField();
        lblCodId = new javax.swing.JLabel();
        txtCodId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(650, 700));
        setMinimumSize(new java.awt.Dimension(650, 700));
        setPreferredSize(new java.awt.Dimension(650, 700));

        Painel_Principal.setBackground(new java.awt.Color(0, 51, 102));
        Painel_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(0, 153, 153));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Title.setText("Editar Cliente");
        header.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 180, 40));

        Painel_Principal.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 40));

        footer.setBackground(new java.awt.Color(0, 153, 153));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setText("Sair");
        exit.addActionListener(this::exitActionPerformed);
        footer.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        Painel_Principal.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 620, 40));

        formPanel.setBackground(new java.awt.Color(0, 153, 153));
        formPanel.setMaximumSize(new java.awt.Dimension(600, 850));
        formPanel.setMinimumSize(new java.awt.Dimension(600, 850));
        formPanel.setPreferredSize(new java.awt.Dimension(600, 850));
        formPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblNome.setText("Nome");
        formPanel.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 180, 25));
        formPanel.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 350, 25));

        lblCategoria.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblCategoria.setText("Categoria");
        formPanel.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 180, 25));
        formPanel.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 350, 25));

        lblDataNasc.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDataNasc.setText("Data de Nascimento");
        formPanel.add(lblDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 25));

        lblNif.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblNif.setText("NIF");
        formPanel.add(lblNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, 25));
        formPanel.add(txtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 350, 25));
        formPanel.add(txtNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 350, 25));

        lblEmail.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblEmail.setText("Email");
        formPanel.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 180, 25));

        lblGenero.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblGenero.setText("Gênero");
        formPanel.add(lblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 25));

        lblcartaoId.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblcartaoId.setText("CartãoId");
        formPanel.add(lblcartaoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 180, 25));

        lblTelefone.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblTelefone.setText("Telefone");
        formPanel.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 180, 25));
        formPanel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 350, 25));
        formPanel.add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 350, 25));
        formPanel.add(txtCartaoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 350, 25));
        formPanel.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 350, 25));

        lblRedesSociais.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblRedesSociais.setText("Redes Sociais");
        formPanel.add(lblRedesSociais, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 180, 25));
        formPanel.add(txtRedesSociais, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 350, 25));

        lblMorada.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblMorada.setText("Morada");
        formPanel.add(lblMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 180, 25));
        formPanel.add(txtMorada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 350, 25));

        lblZonaPostal.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblZonaPostal.setText("Zona Postal");
        formPanel.add(lblZonaPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 180, 25));

        lblCodigoPostal.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblCodigoPostal.setText("Código Postal");
        formPanel.add(lblCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 180, 25));
        formPanel.add(txtZonaPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 350, 25));
        formPanel.add(txtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 350, 25));

        lblNacionalidade.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblNacionalidade.setText("Nacionalidade");
        formPanel.add(lblNacionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 180, 25));

        lblPais.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblPais.setText("País");
        formPanel.add(lblPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 180, 25));

        lblimagem.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblimagem.setText("Imagem");
        formPanel.add(lblimagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 180, 25));

        lblObs.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblObs.setText("OBS");
        formPanel.add(lblObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, 180, 25));
        formPanel.add(txtNacionalidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 350, 25));
        formPanel.add(txtPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 350, 25));
        formPanel.add(txtimagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 670, 350, 25));
        formPanel.add(txtObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 710, 350, 25));

        Voltar.setText("Voltar");
        Voltar.addActionListener(this::VoltarActionPerformed);
        formPanel.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 760, -1, -1));

        Enviar.setText("Enviar");
        Enviar.addActionListener(this::EnviarActionPerformed);
        formPanel.add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 760, -1, -1));

        lblDataRegisto.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblDataRegisto.setText("Data de Registo");
        formPanel.add(lblDataRegisto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 180, 25));
        formPanel.add(txtDataRegisto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 350, 25));

        lblCodId.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        lblCodId.setText("Código de Identificação");
        formPanel.add(lblCodId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 180, 25));
        formPanel.add(txtCodId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 240, 25));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        formPanel.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        delete.setText("Excluir");
        delete.addActionListener(this::deleteActionPerformed);
        formPanel.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 760, -1, -1));

        scrollPane.setViewportView(formPanel);

        Painel_Principal.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 600, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
        new Pagina_Principal().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        //OP.updateCliente(SOMEBITS, nome_cliente, categoria_cliente, data_nasc, WIDTH, email, genero, PROPERTIES, HIDE_ON_CLOSE, redes_sociais, morada, NORMAL, NORMAL, nacionalidade, pais, data_registo, imagem, OBS);
        
        OP.updateCliente(
    Integer.parseInt(txtCodId.getText()),
    txtNome.getText(), 
    txtCategoria.getText(), 
    java.sql.Date.valueOf(txtDataNasc.getText()),   // String -> Date
    Integer.parseInt(txtNif.getText()), 
    txtEmail.getText(), 
    txtGenero.getText(), 
    Integer.parseInt(txtCartaoId.getText()), 
    Integer.parseInt(txtTelefone.getText()), 
    txtRedesSociais.getText(), 
    txtMorada.getText(), 
    Integer.parseInt(txtZonaPostal.getText()), 
    Integer.parseInt(txtCodigoPostal.getText()), 
    txtNacionalidade.getText(), 
    txtPais.getText(), 
    java.sql.Date.valueOf(txtDataRegisto.getText()), // String -> Date
    txtimagem.getText(), 
    txtObs.getText()
);
    }//GEN-LAST:event_EnviarActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarActionPerformed(evt);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        OP.deleteCliente(Integer.parseInt(txtCodId.getText()));
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CL_updt().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enviar;
    private javax.swing.JPanel Painel_Principal;
    private javax.swing.JLabel Title;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel header;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCodId;
    private javax.swing.JLabel lblCodigoPostal;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblDataRegisto;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblMorada;
    private javax.swing.JLabel lblNacionalidade;
    private javax.swing.JLabel lblNif;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblRedesSociais;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblZonaPostal;
    private javax.swing.JLabel lblcartaoId;
    private javax.swing.JLabel lblimagem;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField txtCartaoId;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodId;
    private javax.swing.JTextField txtCodigoPostal;
    private javax.swing.JTextField txtDataNasc;
    private javax.swing.JTextField txtDataRegisto;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtMorada;
    private javax.swing.JTextField txtNacionalidade;
    private javax.swing.JTextField txtNif;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtObs;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtRedesSociais;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtZonaPostal;
    private javax.swing.JTextField txtimagem;
    // End of variables declaration//GEN-END:variables
}
