
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno1
 */
public class SN_updt extends javax.swing.JFrame {
    
    public crud_db OP = new crud_db();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pagina_Principal.class.getName());

    
    
    /**
     * Creates new form Pagina_Principal
     */
    
    crud_db crud = new crud_db();
    
    public SN_updt() {
        initComponents();
       // if(crud.conectar);
// Redimensiona para 20x20 pixels
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Principal = new javax.swing.JPanel();
        online = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtunidade = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        Enviar = new javax.swing.JButton();
        txtnome = new javax.swing.JTextField();
        LB_nome = new javax.swing.JLabel();
        LB_nome1 = new javax.swing.JLabel();
        LB_nome2 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        LB_nome3 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();
        BTexcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(512, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Painel_Principal.setBackground(new java.awt.Color(0, 51, 102));
        Painel_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        online.setText("Online");
        Painel_Principal.add(online, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        footer.setBackground(new java.awt.Color(0, 153, 153));
        footer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setText("Sair");
        exit.addActionListener(this::exitActionPerformed);
        footer.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        Painel_Principal.add(footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 480, 40));

        header.setBackground(new java.awt.Color(0, 153, 153));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        Title.setText("Alterar Sensor");
        header.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 140, 40));

        Painel_Principal.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 40));

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtunidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 170, 30));
        jPanel1.add(txttipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 170, 30));

        Enviar.setText("Enviar");
        Enviar.addActionListener(this::EnviarActionPerformed);
        jPanel1.add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, -1, -1));
        jPanel1.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 170, 30));

        LB_nome.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        LB_nome.setText("Nome:");
        jPanel1.add(LB_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 60, 30));

        LB_nome1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        LB_nome1.setText("Unidade:");
        jPanel1.add(LB_nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, 30));

        LB_nome2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        LB_nome2.setText("Tipo:");
        jPanel1.add(LB_nome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 60, 30));

        Voltar.setText("Voltar");
        Voltar.addActionListener(this::VoltarActionPerformed);
        jPanel1.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        LB_nome3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        LB_nome3.setText("Código:");
        jPanel1.add(LB_nome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 90, 30));
        jPanel1.add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 170, 30));

        BTexcluir.setText("Excluir");
        BTexcluir.addActionListener(this::BTexcluirActionPerformed);
        jPanel1.add(BTexcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        Painel_Principal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 460, 380));

        getContentPane().add(Painel_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed

    OP.updateSensor(Integer.parseInt(txtcod.getText()) , txtnome.getText(), txttipo.getText(), Integer.parseInt(txtunidade.getText()));
    }//GEN-LAST:event_EnviarActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
        new Pagina_Principal().setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    private void BTexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTexcluirActionPerformed
       OP.deleteSensor(Integer.parseInt(txtcod.getText()));
    }//GEN-LAST:event_BTexcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pagina_Principal().setVisible(true));
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTexcluir;
    private javax.swing.JButton Enviar;
    private javax.swing.JLabel LB_nome;
    private javax.swing.JLabel LB_nome1;
    private javax.swing.JLabel LB_nome2;
    private javax.swing.JLabel LB_nome3;
    private javax.swing.JPanel Painel_Principal;
    private javax.swing.JLabel Title;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton exit;
    private javax.swing.JPanel footer;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel online;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txttipo;
    private javax.swing.JTextField txtunidade;
    // End of variables declaration//GEN-END:variables
}
